apiVersion: v1
kind: Service
metadata:
  name: cake-shop-frontend-service
spec:
  selector:
    app: cake-shop-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30008
  type: NodePort